spring:
  application:
    title: OGQ Market
    name: Relay-API
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: DETECT
  rabbitmq:
    host: localhost
    port: 5672
    virtualHost: market
    username: rabbitmqogq
    password: rabbitmqogq

datasource:
  account:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:h2:mem:content;INIT=RUNSCRIPT FROM '../config-repository/sql/account.sql'\;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  content:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:h2:mem:content;INIT=RUNSCRIPT FROM '../config-repository/sql/content.sql'\;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  hash:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:h2:mem:content;INIT=RUNSCRIPT FROM '../config-repository/sql/hash.sql'\;
    driver-class-name: org.h2.Driver
    username: sa
    password: password

logging:
  #pattern:
  #console: "[%-5level %d{yyyy-MM-dd HH:mm:ss}] [%-8thread] [%logger{0}:%line] - %msg%n"
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
    com:
      ogqcorp: DEBUG
